/* Jeux de poésie : les données du texte restent dans js/data/poesies.js. */
let currentPoesie=null, poetryMode='menu', poetryPuzzle=[], poetryPuzzleStanza=0;
let poetryFillLevel=1, poetryFillHoles=[], poetryKaraokeVisited=new Set(), poetryQuizIndex=0, poetryQuizScore=0;

function poetryStart(id='poesie1') { currentPoesie=POESIES.find(p=>p.id===id)||POESIES[0]; document.getElementById('poesie-list').classList.add('hidden'); document.getElementById('poesie-workspace').classList.remove('hidden'); renderPoetryMenu(); }
function poetryClose() { document.getElementById('poesie-workspace').classList.add('hidden'); document.getElementById('poesie-list').classList.remove('hidden'); document.getElementById('poesie-stage').innerHTML=''; document.getElementById('poesie-menu').classList.remove('hidden'); const a=poetryAudio(); if(a)a.pause(); setGameActive(null); }
function poetryAudio() { return document.getElementById('poesie-audio'); }
function verses() { return currentPoesie.stanzas.flat(); }
function renderPoetryMenu() { document.getElementById('poesie-menu').classList.remove('hidden'); document.getElementById('poesie-stage').innerHTML=''; document.getElementById('poesie-title').textContent=currentPoesie.title; document.getElementById('poesie-author').textContent=currentPoesie.author; }
function startPoetryMode(mode) { poetryMode=mode; document.getElementById('poesie-menu').classList.add('hidden'); setGameActive('poesie'); if(mode==='karaoke'){poetryKaraokeVisited=new Set();renderPoetryKaraoke();} if(mode==='quiz'){poetryQuizIndex=0;poetryQuizScore=0;renderPoetryQuiz();} if(mode==='puzzle'){poetryPuzzleStanza=0;renderPoetryPuzzle();} if(mode==='fill'){poetryFillLevel=1;renderPoetryFill();} }
function poetryBackMenu() { const a=poetryAudio(); if(a)a.pause(); renderPoetryMenu(); }
function color(i) { return ['bg-indigo-50 border-indigo-200','bg-emerald-50 border-emerald-200','bg-amber-50 border-amber-200','bg-rose-50 border-rose-200'][i]; }
function structure(html,cls='',includeAuthor=true) { return `<div class="poetry-structure ${cls}"><div class="font-extrabold text-lg text-slate-800 mb-3">${currentPoesie.title}</div>${html}${includeAuthor ? `<div class="font-extrabold text-right mt-3 text-slate-700">${currentPoesie.author}</div>` : ''}</div>`; }

/* Une seule réussite par mode est comptée ; le badge final exige les quatre modes. */
function completePoetryGame(mode,points) { const p=getProfile(); p.poetryStats=p.poetryStats||{completed:[],points:0}; if(p.poetryStats.completed.includes(mode))return; p.poetryStats.completed.push(mode); p.poetryStats.points=(p.poetryStats.points||0)+points; p.points+=points; dailyRecord('poesie',points); saveData(); if(typeof awardBadge==='function'){ if(p.poetryStats.completed.length>=1)awardBadge('poetry_1','Premier poème appris 🎨','Une activité de poésie terminée.','poesie'); if(p.poetryStats.completed.length>=4)awardBadge('poetry_4','Poète accompli ✨','Les quatre activités de poésie terminées.','poesie'); } }

/* Puzzle progressif : une seule strophe est affichée et validée à la fois. */
function renderPoetryPuzzle() { const si=poetryPuzzleStanza, stanza=currentPoesie.stanzas[si]; poetryPuzzle=stanza.map((line,i)=>({line,i})).sort(()=>Math.random()-.5); document.getElementById('poesie-stage').innerHTML=`<div class="bg-amber-50 border border-amber-200 rounded-2xl p-3 text-sm">Strophe ${si+1}/4 : remets uniquement ces vers dans le bon ordre.</div><div id="poetry-puzzle-bank" class="space-y-2 mt-3"></div><div id="poetry-puzzle-answer" class="space-y-2 mt-3 min-h-20 p-3 bg-slate-50 rounded-2xl border-2 border-dashed border-slate-200"></div><div id="poetry-puzzle-feedback" class="min-h-8 mt-3 text-center font-bold"></div><button id="poetry-puzzle-reset" class="poetry-secondary">↩️ Recommencer cette strophe</button><button id="poetry-puzzle-next" class="poetry-primary" disabled>${si===3?'Terminer le poème':'Strophe suivante ➡️'}</button><button class="poetry-secondary" onclick="poetryBackMenu()">✕ Quitter</button>`; const bank=document.getElementById('poetry-puzzle-bank'),answer=document.getElementById('poetry-puzzle-answer'); poetryPuzzle.forEach(x=>{const b=document.createElement('button');b.className='poetry-card';b.textContent=x.line;b.dataset.id=x.i;b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('text/plain',x.i);b.onclick=()=>placePuzzle(x.i);bank.appendChild(b);}); answer.ondragover=e=>e.preventDefault(); answer.ondrop=e=>placePuzzle(Number(e.dataTransfer.getData('text/plain'))); document.getElementById('poetry-puzzle-reset').onclick=resetPoetryStanza; }
function resetPoetryStanza() { const bank=document.getElementById('poetry-puzzle-bank'), answer=document.getElementById('poetry-puzzle-answer'); [...answer.children].forEach(card=>bank.appendChild(card)); document.getElementById('poetry-puzzle-feedback').textContent=''; document.getElementById('poetry-puzzle-feedback').className='min-h-8 mt-3 text-center font-bold'; document.getElementById('poetry-puzzle-next').disabled=true; }
function placePuzzle(id) { const bank=document.getElementById('poetry-puzzle-bank'),answer=document.getElementById('poetry-puzzle-answer'),card=[...bank.children].find(x=>+x.dataset.id===id); if(!card)return; answer.appendChild(card); if(answer.children.length!==poetryPuzzle.length)return; const ok=[...answer.children].every((x,i)=>+x.dataset.id===i),feedback=document.getElementById('poetry-puzzle-feedback'),next=document.getElementById('poetry-puzzle-next'); feedback.textContent=ok?'✅ Strophe correctement remise en ordre !':'❌ Essaie encore : replace les vers.'; feedback.className=`min-h-8 mt-3 text-center font-bold ${ok?'text-emerald-600':'text-rose-600'}`; next.disabled=!ok; if(ok && poetryPuzzleStanza===3){feedback.textContent='🎉 Bravo, tu as remis en ordre tout le poème !';completePoetryGame('puzzle',20);next.disabled=true;} else if(ok) next.onclick=()=>{poetryPuzzleStanza++;renderPoetryPuzzle();}; }

/* Le poème à trous utilise le même clic que le puzzle : un mot puis son emplacement. */
function holes(level) { const out=[]; currentPoesie.stanzas.forEach((s,si)=>s.forEach((line,li)=>{const ts=line.split(/(\s+)/),c=ts.map((t,i)=>({t,i})).filter(x=>/[A-Za-zÀ-ÿ’]/.test(x.t)); const n=level===1?(li%2?1:0):level===2?Math.max(1,Math.round(c.length/3)):Math.max(1,Math.round(c.length/2)); const chosen=level===1?c.slice(-1):c.sort(()=>Math.random()-.5).slice(0,n); chosen.forEach(x=>out.push({si,li,ti:x.i,answer:x.t.replace(/[.,!?;:«»]+$/g,'')}));})); return out; }
function renderPoetryFill() { const hs=poetryFillHoles=holes(poetryFillLevel),map=new Map(hs.map((h,i)=>[`${h.si}-${h.li}-${h.ti}`,{...h,id:i}])); const html=currentPoesie.stanzas.map((s,si)=>`<div class="poetry-fill-stanza ${color(si)}">${s.map((line,li)=>`<div class="poetry-fill-line">${line.split(/(\s+)/).map((t,ti)=>{const h=map.get(`${si}-${li}-${ti}`);return h?`<button class="poetry-blank poetry-dropzone" data-hole="${h.id}">choisis un mot</button>`:t;}).join('')}</div>`).join('')}</div>`).join(''); document.getElementById('poesie-stage').innerHTML=`<div class="bg-violet-50 border border-violet-200 rounded-2xl p-3 text-sm">Niveau ${poetryFillLevel}/3 : touche un mot, puis touche l’espace où tu veux le placer.</div><div id="poetry-fill-bank" class="flex flex-wrap gap-2 mt-3"></div>${structure(html,'mt-3')}<div id="poetry-fill-feedback" class="min-h-8 mt-3 text-center font-bold"></div><button id="poetry-fill-next" class="poetry-primary">Vérifier et continuer ➡️</button><button class="poetry-secondary" onclick="poetryBackMenu()">✕ Quitter</button>`; const bank=document.getElementById('poetry-fill-bank'); /* Fisher-Yates mélange la banque sans modifier les bonnes réponses des cases. */ const shuffled=[...hs]; for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];} if(shuffled.length>1 && shuffled.every((h,i)=>h===hs[i])) [shuffled[0],shuffled[1]]=[shuffled[1],shuffled[0]]; shuffled.forEach(h=>{const b=document.createElement('button');b.className='poetry-card !w-auto';b.textContent=h.answer;b.dataset.wordId=hs.indexOf(h);b.onclick=()=>selectFillWord(b);bank.appendChild(b);}); document.querySelectorAll('.poetry-dropzone').forEach(z=>z.onclick=()=>placeFillWord(z)); document.getElementById('poetry-fill-next').onclick=verifyFill; }
let selectedFillWord=null;
function selectFillWord(button) { document.querySelectorAll('#poetry-fill-bank .poetry-card').forEach(b=>b.classList.remove('selected')); button.classList.add('selected'); selectedFillWord=button; }
function placeFillWord(zone) { if(!selectedFillWord)return; zone.textContent=selectedFillWord.textContent;zone.dataset.value=selectedFillWord.textContent;zone.dataset.wordId=selectedFillWord.dataset.wordId;selectedFillWord.classList.add('hidden');selectedFillWord=null;document.querySelectorAll('#poetry-fill-bank .poetry-card').forEach(b=>b.classList.remove('selected')); }
function verifyFill() { const hs=poetryFillHoles,bad=[...document.querySelectorAll('.poetry-dropzone')].filter(z=>!z.dataset.value||z.dataset.value.toLowerCase()!==hs[+z.dataset.hole].answer.toLowerCase()),f=document.getElementById('poetry-fill-feedback'); if(bad.length){f.textContent=`Encore un effort : ${bad.length} mot${bad.length>1?'s':''} à replacer.`;f.className='min-h-8 mt-3 text-center font-bold text-rose-600';return;} if(poetryFillLevel<3){poetryFillLevel++;renderPoetryFill();}else{f.textContent='🌟 Niveau 3 terminé !';f.className='min-h-8 mt-3 text-center font-bold text-emerald-600';completePoetryGame('fill',20);} }

/* Karaoké : les valeurs de currentPoesie.timings sont les secondes de début des vers. */
function renderPoetryKaraoke() { const html=currentPoesie.stanzas.map((s,si)=>`<div class="poetry-karaoke-stanza ${color(si)}">${s.map((line,li)=>{const i=currentPoesie.stanzas.slice(0,si).reduce((n,x)=>n+x.length,0)+li;return`<button class="poetry-line poetry-click-line" data-line="${i}">${line}</button>`;}).join('')}</div>`).join(''); document.getElementById('poesie-stage').innerHTML=`<div class="bg-rose-50 border border-rose-200 rounded-2xl p-3 text-sm">Clique sur un vers pour l’écouter à son moment précis.</div><audio id="poesie-audio" controls class="w-full mt-3" src="${currentPoesie.audio}"></audio>${structure(html,'mt-3',false)}<button class="poetry-line poetry-click-line font-extrabold text-right mt-3 text-slate-700" data-line="20">${currentPoesie.author}</button><button class="poetry-secondary" onclick="poetryBackMenu()">✕ Quitter</button>`; const a=poetryAudio();document.querySelectorAll('.poetry-click-line').forEach(b=>b.onclick=()=>{const i=+b.dataset.line;poetryKaraokeVisited.add(i);document.querySelectorAll('.poetry-click-line').forEach(x=>x.classList.toggle('active',+x.dataset.line===i));const t=currentPoesie.timings?.[i];if(Number.isFinite(t)){a.currentTime=t;a.play().catch(()=>{});}if(poetryKaraokeVisited.size===verses().length+1)completePoetryGame('karaoke',20);});a.ontimeupdate=()=>{let active=-1;(currentPoesie.timings||[]).forEach((t,i)=>{if(Number.isFinite(t)&&t<=a.currentTime)active=i;});if(active>=0)document.querySelectorAll('.poetry-click-line').forEach(x=>x.classList.toggle('active',+x.dataset.line===active));}; }

/* QCM de compréhension : les boutons du menu ne sont jamais désactivés. */
function renderPoetryQuiz() { const q=[['Quel instrument est cité dans la première strophe ?',['Une guitare','Un violon','Un tambour'],'Une guitare'],['Que peut remplacer un poème ?',['Quelques larmes','Les devoirs','Un arc-en-ciel'],'Quelques larmes'],['Le poème est décrit comme un voyage…',['extérieur','intérieur','spatial'],'intérieur'],['À quoi sert aussi un poème à la fin ?',['À dire « Je t’aime »','À dormir','À courir'],'À dire « Je t’aime »'],['Avec quoi la vie est-elle comparée ?',['Un tour de magicien','Une montagne','Un château'],'Un tour de magicien']];const [question,opts,answer]=q[poetryQuizIndex];document.getElementById('poesie-stage').innerHTML=`<div class="bg-sky-50 border border-sky-200 rounded-2xl p-3 text-sm">Question ${poetryQuizIndex+1}/${q.length} · ${poetryQuizScore} bonne${poetryQuizScore>1?'s':''} réponse${poetryQuizScore>1?'s':''}</div><p class="text-lg font-bold text-slate-800 mt-4">${question}</p><div id="poetry-quiz-options" class="grid gap-2 mt-3"></div><div id="poetry-quiz-feedback" class="min-h-8 mt-3 text-center font-bold"></div><button class="poetry-secondary" onclick="poetryBackMenu()">✕ Quitter</button>`;const box=document.getElementById('poetry-quiz-options');opts.forEach(o=>{const b=document.createElement('button');b.className='poetry-option';b.textContent=o;b.onclick=()=>answerPoetryQuiz(b,o,answer,q.length);box.appendChild(b);}); }
function answerPoetryQuiz(button,answer,expected,total) { const options=[...document.querySelectorAll('#poetry-quiz-options .poetry-option')];if(options.some(b=>b.disabled))return;options.forEach(b=>b.disabled=true);const f=document.getElementById('poetry-quiz-feedback');if(answer===expected){poetryQuizScore++;button.classList.add('correct');f.textContent='✅ Bravo !';f.className='min-h-8 mt-3 text-center font-bold text-emerald-600';}else{button.classList.add('wrong');f.textContent=`❌ La réponse était : ${expected}`;f.className='min-h-8 mt-3 text-center font-bold text-rose-600';}setTimeout(()=>{if(poetryQuizIndex<total-1){poetryQuizIndex++;renderPoetryQuiz();}else{f.textContent=`🎉 Série terminée : ${poetryQuizScore}/${total}`;completePoetryGame('quiz',poetryQuizScore*5);}},700); }
function nextPoetryFill(){verifyFill();}
